### ISSUE TITLE
Bot wallhack

### ISSUE THREAD

**Issue by mack31** [zeal1209/XFakePlayers#3]
Hi zeal1209

How can i setup the bots so they can see you over the walls.
Ive tested and it seems that the bots have wallhack.
They starts to shoot before actual seeing you.

Thankyou

**Comment by zeal1209** [comment]
Hello, mack31!

Bot can see player through walls when IsEntityActive() return 'true'. If *.bsp map loaded - bot using IsVisible() function to check enemy visibility from bot's eyes.

The "IsVisible()" function is analog of "SV_RecursiveHullCheck" from original HLDS, which was (re)implemented by me. As bot does not load models - function can not check the visibility through them. This means that the bot will see players through objects, such as windows, breakable boxes at bomb places, trees, cars, (and any other non-brush object at map).

So, if you want to add wallhack to bots - you need to find "FindVictim()" function in utils.lua (line 460), and rewrite: "Victim = NearestVisibleEnemy" to "Victim = NearestEnemy".

**Comment by mack31** [comment]
I dont want to add wallhack to bots.
My actual problem is that the bots allready have wallhack activated.

Can you please advice me how to make the bots more realistic?

**Comment by mack31** [comment]
Hi zeal1209

Ive solve the wallhack problem.
One more question.

For exemple:
Current map: fy_snow
Waypoints: missing or do not exist.

How can i set the bots still walking on the map with no waipoints?

Is there any way to auto create waipoints or download them?

**Comment by zeal1209** [comment]
Hello, mack31!

To create navigation map you need to run *.bsp map under Counter-Strike: Condition Zero with built in game bots (or CS 1.6 with ZBot). Navigation map will be automatically generated after server started and saved in "...\czero\maps\%MAPNAME%.nav". Then you need to move the navigation map from game dir to "XFakePlayers\navigations\".

**Comment by mack31** [comment]
I see.
Tkankyou for all your help and time.
